version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/test-nodejs

hooks:
  BeforeInstall:
    - location: installDep.sh
      runas: ec2-user
  ApplicationStart:
    - location: run.sh
      runas: ec2-user
