version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/lol/test-nodejs

hooks:
  AfterInstall:
    - location: installDep.sh
      runas: ec2-user
  ApplicationStart:
    - location: run.sh
      runas: ec2-user
